[tool.poetry]
name = "biopipen"
version = "0.1.0"
description = "Bioinformatics processes/pipelines that can be run from `pipen run`"
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
pipen = "^0.2"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins.pipen_cli_run]
vcf = "biopipen.namespaces.vcf"
bed = "biopipen.namespaces.bed"
tcr = "biopipen.namespaces.tcr"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
