[tool.poetry]
name = "biopipen"
version = "0.0.1"
description = "A set of PyPPL processes for bioinformatics."
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"
include = [
"biopipen/scripts/*/*",
"biopipen/utils/*/*",
"biopipen/reports/*/*",
"biopipen/params.toml"
]
exclude = ["biopipen/**/*.pyc"]

[tool.poetry.dependencies]
python = "^3.6"
pipen = "*"
pyparam = "*"
diot = "*"
modkit = "*"
toml = "0.*" # 0.10.1 has a bug: https://github.com/uiri/toml/issues/295
pipen-annotate = "*"
rich = "9.*"

[tool.poetry.scripts]
biopipen = 'biopipen.cli:main'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
