[tool.poetry]
name = "bioprocs"
version = "0.1.2"
description = "A set of PyPPL processes for bioinformatics."
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"
include = [
	"bioprocs/scripts/*/*",
	"bioprocs/utils/*/*",
	"bioprocs/reports/*/*",
	"bioprocs/params.toml"
]
exclude = ["bioprocs/**/*.pyc"]

[tool.poetry.dependencies]
python = "^3.6"
PyPPL = "3.*"
pyparam = "*"
diot = "*"
completions = "*"
toml = "0.*"
pyppl_annotate = "*"
pyppl_export = "*"
pyppl_report = "*"

[tool.poetry.scripts]
bioprocs = 'bioprocs.console:main'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
