[tool.poetry]
name = "bioprocs"
version = "0.1.0"
description = "A set of PyPPL processes for bioinformatics."
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"
include = [
	"bioprocs/scripts/*/*",
	"bioprocs/utils/*/*"
]
exclude = [
	"bioprocs/**/*.pyc"
]

packages = [
	{ include = "bioprocs" },
	{ include = "bioprocs.console" },
	{ include = "bioprocs.console.pipeline" },
	{ include = "bioprocs.sets" }
]

[tool.poetry.dependencies]
python = "^3.6"
PyPPL = "*"
pyparam = "*"
python-box87 = "*"
completions = "*"

[tool.poetry.scripts]
bioprocs = 'bioprocs.console:main'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
